#!\bin\bash

#modes :
stat -c%a test

#taille :
stat -c%B test

#date de modif :
stat -c%y test


name="name :"$(stat -c%n $fich)
mode="mode: "$(stat -c%a $fich)
taille="taille: "$(stat -c%B $fich)
date="date: "$(stat -c%y $fich)

line="${name} ${mode} ${taille} ${date}"

echo $line >> journal
